### ISSUE TITLE
Unknown character in config file

### ISSUE THREAD

**Issue by SilverSix311** [madslundt/cloud-media-scripts#10]
Hey,
Still somewhat new with git stuff, and don't really know how to pull and make changes and commit em (haven't spent much time looking it either). But anyways, there seems to be a weird character in the config file. I noticed it created a folder named "plexdrive?" and it's not usable. Here is what it looks like:
```
# Local directory
local_decrypt_dir="${media_dir}/.local-decrypt/Media"
plexdrive_temp_dir="${media_dir}/.local-decrypt/plexdrive"â€‹
```
Changing to this seems to be fine, not sure where it comes from tho.
```
# Local directory
local_decrypt_dir="${media_dir}/.local-decrypt/Media"
plexdrive_temp_dir="${media_dir}/.local-decrypt/plexdrive"
```
It isn't visible in nano when opening the script on debian, but there is definitely some kind of character there as i can delete the "blank" characters within nano. Either way, just wanted to help out.

**Comment by madslundt** [comment]
Hi there.

Good catch. I didn't see that and don't know how it was inserted. I've removed the character and it should be all good now.

Thank you very much!
