### ISSUE TITLE
Issue removing files with rmlocal.

### ISSUE THREAD

**Issue by SilverSix311** [madslundt/cloud-media-scripts#12]
So I got all my stuff uploaded to google drive now, but when the rmlocal script runs I receive the following error:
```
du: cannot access ‘'   /mnt/Library/Plex-Servers/PleXXX/local-decrypt/PleXXX/[P]/Misc/Season 02/S0002E0006.mp4'’: No such file or directory
/mnt/Library/Plex-Servers/PleXXX/scripts/rmlocal: line 126: 0 + : syntax error: operand expected (error token is "+ ")
```

Looking at the scripts, I think it has to do with the escape characters not existing when using $n as a parameter for ``fileSize=$(du -sb "$n" | awk '{print $1}')`` on line 124.

```
	find "${local_decrypt_dir}" -type f -exec stat -c "%x %n" {} \; | sort | awk '{$1=$2=$3=""; print $0}' |
		while IFS= read -r n; do
			if [ "$addedSpace" -gt "$freeup" ]; then
					spaceInGb=$(($addedSpace / 1000 / 1000 / 1000))

					spaceLeft=$(($(du -sb "$local_decrypt_dir" | awk '{print $1}') / 1000 / 1000 / 1000))
					echo "[ $(date ${date_format}) ] Removed ${spaceInGb} GB. Media in total ${spaceLeft} GB."
					break
			fi
```

**Comment by SilverSix311** [comment]
Soo looking into the file is was referencing, there were 2 spaces back to back in the file for some reason. It couldn't handle processing that file due to that.

**Comment by madslundt** [comment]
I'll add a trim function to remove spaces

**Comment by madslundt** [comment]
Would it be possible for you to add ` xargs |` to line 91 in rmlocal, so it looks like `find "${local_decrypt_dir}" -type f -exec stat -c "%x %n" {} \; | sort | awk '{$1=$2=$3=""; print $0}' | xargs |` and then try again?

If that doesn't work a final attempt would be to add following code to line 99 in rmlocal and try again: `n=$(echo "$n" | xargs)`

**Comment by SilverSix311** [comment]
Tried both, and it is still having issues. The current way works fine, but only if my files don't have 2 spaces back to back. Which they shouldn't anyway, so it's been pointing me to each file that I need to fix anyway with the logs. If you want to fix that issue, that's up to you. I'm just fixing the one of files I have when it errors out in the script.

Kept giving the ``du has no access`` error.
