### ISSUE TITLE
mount.remote - Could not find encrypted mountpoint: /home/services/cloud-media-scripts/.cloud-decrypt

### ISSUE THREAD

**Issue by MadMooAU** [madslundt/cloud-media-scripts#13]
When running mount.remote, after using setup.sh, the first mount (.cloud-encrypt) and second mount (.cloud-decrypt) succeed, then .cloud-decrypt cannot be found.

Fresh Ubuntu 16.04 install, running from root for testing.
```
[ 2017-10-19@03:46:45 ] ###### Start Mount ######
[ 2017-10-19@03:46:50 ] Mounting Google Drive with Plexdrive in mountpoint: /home/services/cloud-media-scripts/.cloud-encrypt
[ 2017-10-19@03:46:50 ] Mounted successfully with Plexdrive
[ 2017-10-19@03:46:55 ] Mounting decrypted Google Drive with Rclone in mountpoint: /home/services/cloud-media-scripts/.cloud-decrypt
[ 2017-10-19@03:46:55 ] Mounted successfully with Rclone
```

**Comment by madslundt** [comment]
Have you configured Rclone properly? And can you verify that there is data in .cloud-encrypt?

**Comment by MadMooAU** [comment]
I've followed the setup.sh guide after using the easy install script. cloud-encrypt is mounted, data is in there.

**Comment by MadMooAU** [comment]
It's the mount_union subroutine, after removing 
```
		while [ -z "$(ls -A ${cloud_decrypt_dir})" ]
		do
			echo "[ $(date ${date_format}) ] Cloud not find encrypted mountpoint: ${cloud_decrypt_dir}. Retrying in 10 seconds."
			sleep 10
		done
```
it works.

**Comment by madslundt** [comment]
For what I can understand is that Plexdrive mounts .cloud-encrypt but seems like Rclone doesn't mount .cloud-decrypt. That to me sounds like a misconfiguration in Rclone. When running the setup.sh did you configure rclone with the correct encryption/decryption keys?

**Comment by madslundt** [comment]
Okay thank you for pointing out the error. I'll look into that
