### ISSUE TITLE
Add requirements section

### ISSUE THREAD

**Issue by Antexa** [madslundt/cloud-media-scripts#15]
Is this possible to add a requirements section to the readme

I run into a loop trouble with the mongoDB, and we didn't get log to get the behavior quickly, maybe a good point to add log on plexdrive and rclone 

Good work @madslundt  👍

**Comment by madslundt** [comment]
Good idea. I'll add the option to run the scripts with verbose

**Comment by Antexa** [comment]
What do you think about adding the installation of mongodb in the easy install way ?

This could allow user to have a plug and play way

**Comment by madslundt** [comment]
I'm already working on asking the user to install mongodb in the easy install :)
