### ISSUE TITLE
Permissions issue?

### ISSUE THREAD

**Issue by Dulanic** [madslundt/cloud-media-scripts#16]
I am running into a permission issue /w local-media folder. For some reason radarr keeps getting permission denials with directory. Radarr is run in docker.
`
Couldn't import episode /downloads/complete/tv/redacted: Access to the path "/tv/redacted is denied.`

All source files in /downloads are owned by user 1000. /tv is a docker folder that is mapped to /local-media/Media/Shows. It seems like there is a write issue to local-media for some reason? That should write it to my local-decrypt?

**Comment by madslundt** [comment]
Did you run the scripts with user 1000 and are you able to copy stuff into /local-media outside docker?

**Comment by Dulanic** [comment]
They run as a cron job as root. I also could copy outside of docker so it was driving me crazy. What I ended up doing is adding --uid=1000 to my rclone options and that fixed it.

**Comment by madslundt** [comment]
Okay. I'll point that out in the documentation. Thanks!

**Comment by Dulanic** [comment]
ignore open new issue since cant reopen
