### ISSUE TITLE
Config change, and suggestion

### ISSUE THREAD

**Issue by SilverSix311** [madslundt/cloud-media-scripts#26]
I would recommend changing a few things in your main Config file and then in your setup.sh. I would do this myself, but honestly don't use github enough to know how to properly do pulls and commits.

I would recommend adding a "install_folder" variable that will contain only cloud-media-scripts contents so it is separate from any "Media."

I modified it and have it working on my end, but I run my VM on a different device than my storage. I would also recommend putting in a mount option for your media as well and have that built into the "mount.remote" script. This mount would allow you to mount your media directories directly into your local-decrypt folder.

```
#!/bin/bash
# shellcheck disable=SC2034
###############################################################################
# DIRECTORIES
###############################################################################
media_dir="/mnt/Library"
install_dir="/opt/cloud-media-scripts"

# Cloud directories
cloud_encrypt_dir="${media_dir}/.cloud-encrypt"
cloud_decrypt_dir="${media_dir}/.cloud-decrypt"

# Local directory
local_decrypt_dir="${media_dir}/.local-decrypt/Media"
plexdrive_temp_dir="${media_dir}/.local-decrypt/plexdrive"

# Media directory (FINAL)
local_media_dir="${media_dir}/media"


# Encrypt media (0 means no encryption)
encrypt_media=0
```

I then replaced all the ${media_dir} with ${install_dir} so that rclone/plexdrive install into the scripts folder rather than having it install into the "Media" folder as well. To me its cleaner, and you can move things around without breaking stuff. The only issue you run into with this is using fstab to mount your directories. You will need to have your rclone/plexdrive mounted before you can mount your Media into local-decrypt.

*EDIT* - Not all instances of ${media_dir} were changed, only the ones that were relevant.

Example of setup.sh attached.
[setup.zip](https://github.com/madslundt/cloud-media-scripts/files/1447588/setup.zip)

My current setup is like this:

/mnt/Library/.local-decrypt/
/mnt/Library/.cloud-decrypt/
/mnt/Library/media/

Then after mount.remote is run, I have my media mounted into /mnt/Library/.local-decrypt/

This way I have my already setup media being moved into the cloud without killing my currently running plex. All my media is still in the same location on my NAS, and when it finishes uploading I can just switch my library locations very easily.

This is how I set this up for me, so you may or may not see any of this as helpful.

**Comment by madslundt** [comment]
Great idea by having the scripts in a directory of its own. I agree that by doing this it will look less messy.
I'll look into your setup.zip file this weekend when I get some spare time. Thank you for your contribution
