### ISSUE TITLE
Missing Directories

### ISSUE THREAD

**Issue by Dulanic** [madslundt/cloud-media-scripts#30]
So at some point I noticed in plex I only had like 2 shows and I wasnt sure why. I ran the mount check and it came back as everything successfully mounted. Obviously something dropped but wasn't catching what dropped. I am assuming it had to be rclone since it was all my gdrive stuff that wasn't showing. 

This also caused radarr/sonarr to go hey missing files, lets go find them again. Any other logs I could pull or things I could look into to see why it didnt identify it as dropped? My plex has been scanning for hours trying to rebuild the metadata lol

I'm not sure what else to check for the root cause? I tried to umount.remote and then mount.remote but it just hang on .cloud-decrypt mounting. But when I reboot the server it mounts no problem.

Status.log:
`[ 2018-01-07@20:15:01 ] /local-media is mounted properly
[ 2018-01-07@20:15:01 ] /opt/cloud/.cloud-encrypt is mounted properly
[ 2018-01-07@20:15:01 ] /opt/cloud/.cloud-decrypt is mounted properly
[ 2018-01-07@20:15:01 ] /chunks is mounted properly
[ 2018-01-07@20:20:01 ] /local-media is mounted properly
[ 2018-01-07@20:20:01 ] /opt/cloud/.cloud-encrypt is mounted properly
[ 2018-01-07@20:20:01 ] /opt/cloud/.cloud-decrypt is mounted properly
[ 2018-01-07@20:20:01 ] /chunks is mounted properly
[ 2018-01-07@20:30:01 ] /local-media is mounted properly
[ 2018-01-07@20:30:01 ] /opt/cloud/.cloud-encrypt is mounted properly
[ 2018-01-07@20:30:01 ] /opt/cloud/.cloud-decrypt is mounted properly
[ 2018-01-07@20:30:01 ] /chunks is mounted properly
[ 2018-01-07@20:35:01 ] /local-media is mounted properly
[ 2018-01-07@20:35:01 ] /opt/cloud/.cloud-encrypt is mounted properly
[ 2018-01-07@20:35:01 ] /opt/cloud/.cloud-decrypt is mounted properly
[ 2018-01-07@20:35:01 ] /chunks is mounted properly
[ 2018-01-07@20:40:01 ] /local-media is mounted properly
[ 2018-01-07@20:40:01 ] /opt/cloud/.cloud-encrypt is mounted properly
[ 2018-01-07@20:40:01 ] /opt/cloud/.cloud-decrypt is mounted properly
[ 2018-01-07@20:40:01 ] /chunks is mounted properly
`

Mount.log - You can see the last time it mounted 2 days ago and it dropped something today, but not sure when.
`[ 2018-01-05@17:26:26 ] ###### Mounted successfully ######
[ 2018-01-05@18:38:11 ] ###### Start Mount ######
[ 2018-01-05@18:38:16 ] Mounting Google Drive with Plexdrive in mountpoint: /opt/cloud/.cloud-encrypt
[ 2018-01-05@18:38:16 ] Mounted successfully with Plexdrive
[ 2018-01-05@18:38:21 ] Mounting decrypted Google Drive with Rclone in mountpoint: /opt/cloud/.cloud-decrypt
[ 2018-01-05@18:38:21 ] Mounted successfully with Rclone
[ 2018-01-05@18:38:26 ] Mounting final library with UnionFS in mountpoint: /local-media
[ 2018-01-05@18:38:26 ] Mounted successfully with UnionFS
[ 2018-01-05@18:38:26 ] ###### Mounted successfully ######
[ 2018-01-07@20:28:59 ] ###### Start Mount ######
[ 2018-01-07@20:29:04 ] Mounting Google Drive with Plexdrive in mountpoint: /opt/cloud/.cloud-encrypt
[ 2018-01-07@20:29:04 ] Mounted successfully with Plexdrive
[ 2018-01-07@20:29:09 ] Mounting decrypted Google Drive with Rclone in mountpoint: /opt/cloud/.cloud-decrypt
[ 2018-01-07@20:29:09 ] Mounted successfully with Rclone
[ 2018-01-07@20:29:14 ] Mounting final library with UnionFS in mountpoint: /local-media
[ 2018-01-07@20:29:14 ] Mounted successfully with UnionFS
[ 2018-01-07@20:29:14 ] ###### Mounted successfully ######`

**Comment by Antexa** [comment]
A commit was helpfull for your behavior. See this PR https://github.com/madslundt/cloud-media-scripts/pull/29

Cheers

**Comment by Dulanic** [comment]
Thanks, will try updating and see how it goes. This was the 1st time in > a month so I'll close this and create a new one if  happens again.

**Comment by Antexa** [comment]
Please notice : this will be helpfull only on plex db and the inconveniant refresh of your metadata. 

You will encounter the same behavior for your missing data on radarr.
