### ISSUE TITLE
Mount dropped and won't remount

### ISSUE THREAD

**Issue by Dulanic** [madslundt/cloud-media-scripts#34]
So this morning I noticed my mount dropped and I tried to run mountcheck and this is all I see...

The only fix was for me to reboot. Mongodb is installed and running properly? Not sure why rebooting fixes it, but the script wont?

```

[ 2018-01-16@11:03:12 ] Mount has dropped. Remount in progress.
[ 2018-01-16@11:03:12 ] Unmounting...
[ 2018-01-16@11:03:12 ] Unmounting decrypted cloud mountpoint -> /opt/cloud/.cloud-decrypt
fusermount: failed to unmount /opt/cloud/.cloud-decrypt: Invalid argument
[ 2018-01-16@11:03:12 ] Unmounting encrypted cloud mountpoint -> /opt/cloud/.cloud-encrypt
fusermount: failed to unmount /opt/cloud/.cloud-encrypt: Invalid argument
[ 2018-01-16@11:03:12 ] Unmounting final library mountpoint -> /local-media
fusermount: failed to unmount /local-media: Invalid argument
[ 2018-01-16@11:03:12 ] Unmounted successfully
[ 2018-01-16@11:03:12 ] Mounting...
[ 2018-01-16@11:03:12 ] ###### Start Mount ######
[ 2018-01-16@11:03:17 ] Could not connect to Mongodb. Retrying in 5 seconds.
[ 2018-01-16@11:03:22 ] Could not connect to Mongodb. Retrying in 5 seconds.
[ 2018-01-16@11:03:27 ] Could not connect to Mongodb. Retrying in 5 seconds.
[ 2018-01-16@11:03:32 ] Could not connect to Mongodb. Retrying in 5 seconds.
[ 2018-01-16@11:03:37 ] Could not connect to Mongodb. Retrying in 5 seconds.
[ 2018-01-16@11:03:42 ] Could not connect to Mongodb. Please make sure Mongodb is running before mounting
[ 2018-01-16@11:03:42 ] Mount failed
[ 2018-01-16@11:03:42 ] Mounted successfully
```

**Comment by Dulanic** [comment]
Keeps happening again... I've tried running mongo as a docker container without success. I cant figure out why the mongodb just seems to stop responding.,..

**Comment by madslundt** [comment]
What version of MongoDb have you installed? Sounds like MongoDb is hanging.
Have you tried to connect to your [MongoDb via Mongo Shell](https://docs.mongodb.com/tutorials/connect-to-mongodb-shell/)?

**Comment by Dulanic** [comment]
I pulled it from the main Mongo repo. I think I might have gotten the docker version working for once, didn't do anything different than before.

**Comment by Dulanic** [comment]
I pulled it from the main Mongo repo. I think I might have gotten the docker version working for once, didn't do anything different than before.

**Comment by Dulanic** [comment]
Has been 3 days, no further issue so closing.
