### ISSUE TITLE
Possible Enhancement - Allow Deletion

### ISSUE THREAD

**Issue by Dulanic** [madslundt/cloud-media-scripts#36]
So I know last year plexidrive added the ability to delete files. I have edited my config etc... to remove ready only and change RO to RW. So far it's working great, 

Am I correct that UFS should write to local-decrypt 1st as UFS lists the local decrypt dir as 1st level? Seems to be working so far. This would allow us to delete in plex and have it remove the files from GD.

My changes currently:
Per testing it is properly loading files to decrypt when downloading.

```
ufs_options="-o cow,allow_other,direct_io,nonempty,auto_cache,sync_read,uid=$uid,gid=$gid"
plexdrive_options="--temp=${plexdrive_temp_dir} -o allow_other --clear-chunk-max-size=300G --clear-chunk-age=24h --chunk-size=10M"
ufs_mounts="${local_decrypt_dir}=RW:${cloud_decrypt_dir}=RW"
```

If you think it's a decent idea to add, I can help code it in the config/mount.remote.

**Comment by madslundt** [comment]
This would of course only work if the user aren't using encryption.

It's a great idea and if you have the time hit me with a PR.

**Comment by Dulanic** [comment]
Actually, that's not correct. It works with encryption. With encryption rclone passes the delete to plexdrive which passes it to GD.

Maybe this should just be coded this way permanently since the writes still default to the 1st path on unionfs.

![image](https://user-images.githubusercontent.com/2948206/36152957-5c943b4c-1092-11e8-8904-8ed5b8d79c8a.png)

![image](https://user-images.githubusercontent.com/2948206/36152987-753fec5e-1092-11e8-815e-ff0445c79885.png)

**Comment by madslundt** [comment]
Oh yeah I see of course. My mistake

**Comment by Dulanic** [comment]
Found another major help of doing it this way. Sonarr/Radarr can delete old versions if it is upgrading. I noticed I had like 4 copies of movies before and this resolves that problem.

**Comment by Dulanic** [comment]
Closing as merged.
