### ISSUE TITLE
Buffering issue

### ISSUE THREAD

**Issue by alxdca** [madslundt/cloud-media-scripts#39]
I've experienced several buffering issues when using google drive as storage. Plexdrive has an option named 'chunk-load-ahead'. Could you expose it ?

By the way, I've seen that your merged a PR allowing deletion on the cloud mount. Would that work with google drive ? At the moment, when radarr/sonarr replaces content, I get a duplicate file on google drive as it can't delete the old. Would that PR fix this ?

**Comment by Dulanic** [comment]
I coded the deletion part and it seems to be working for me so far. It does work for radarr/sonarr for me. I'm hoping it doesn't have unintended consequences, so far so good for me.

chunk-load-ahead you can add in config
