### ISSUE TITLE
Rclone.conf issue /w setup.sh

### ISSUE THREAD

**Issue by Dulanic** [madslundt/cloud-media-scripts#41]
Hey madslundt. So when I was playing around with my fork I noticed that the rclone.conf was not properly setting the local-crypt and was missing the GD folder after the local-crypt even though it shows it in the template. I tried to look through to see how you set that, but didn't figure it out off hand. Want to take a look at that?

```
[local-crypt]
type = crypt
remote = /opt/cloud-media-scripts/.cloud-encrypt
filename_encryption = standard
```

`remote = <ENCRYPTED_FOLDER>/**<GOOGLE_DRIVE_MEDIA_DIRECTORY>**`

FYI, my googledrive in config is Media.

**Comment by madslundt** [comment]
I just tried on the latest version and it sets the remote correct.
Do you have the latest setup.sh and rclone.template.conf?

**Comment by Dulanic** [comment]
So odd, I ran it again and it worked this time. I know it was same commands. Can't repeat so closing.
