### ISSUE TITLE
Plexdrive

### ISSUE THREAD

**Issue by pcs333** [madslundt/cloud-media-scripts#46]
Hi
Can I use this with plexdrive 5 ?
I already have version 5 setup and I have no root access.

**Comment by Dulanic** [comment]
You'd need to alter the scripts. 4.0 is used as it's stable uses less memory. Lots have asked for 5 but madslundt is happy with 4 as are some others. Maybe eventually someone will do a PR to add it, but don't think it will be madslundt. I don't see the need yet myself so I'm not doing the PR either.

**Comment by pcs333** [comment]
Yeah I thought that after looking through the scripts.
It's not too difficult to alter. The main thing is adding "mount" on the plexdrive line in the mount.remote script.
Cheers
