### ISSUE TITLE
[MergerFS] Input/output error

### ISSUE THREAD

**Issue by Antexa** [madslundt/cloud-media-scripts#47]
I recently upgraded to the version using MergerFS. It turns out that I have the following error when copying a file : 

```
root@1696351a9d23:/input cp /input/aFile.test /output/aFile.test
cp: error writing ‘/output/aFile.test’: Input/output error
cp: failed to extend ‘/output/aFile.test’: Input/output error
cp: failed to close ‘/output/aFile.test’: Input/output error
root@1696351a9d23:/input#
```

@Dulanic Looks like there's a connection between my mistake and the issue you reported on the MergerFS github.

https://github.com/trapexit/mergerfs/issues/466

**Comment by Dulanic** [comment]
So what I found on my side is I had to chown my decrypt dir. Trying to see if that's a settings issue or something else.

**Comment by Antexa** [comment]
What do you mean by chown your decrypt dir ? 

```
user@computer:~/cloud$ ls -la 
total 680
drwxr-xr-x 12 user user   4096 Mar 12 10:21 .
drwxr-xr-x 22 user user   4096 Mar 12 16:23 ..
drwxr-xr-x  1 user user      0 Mar 12 11:09 .cloud-decrypt
drwxr-xr-x  1 user user      0 May 23  2017 .cloud-encrypt
-rw-r--r--  1 user user   3906 Mar 12 11:08 config
```

**Comment by Dulanic** [comment]
Can you comment what your mergerfs process command looks like?

` ps aux | less | grep mergerfs`

**Comment by Antexa** [comment]
```
user@computer:~/cloud/.cloud-decrypt$ ps aux | less | grep mergerfs
user   3177  0.0  0.0  12788   984 pts/1    S+   17:36   0:00 grep mergerfs
user   3299  0.1  0.0 620248  5800 ?        Ssl  11:09   0:41 /usr/bin/mergerfs -o defaults,nonempty,allow_other,direct_io,use_ino,uid=1000,gid=1000 /home/user/cloud/.local-decrypt/Media:/home/user/cloud/.cloud-decrypt:RO /home/user/cloud/media

user@computer:~/cloud/.cloud-decrypt$ id
uid=1000(user) gid=1000(user) groups=1000(user),27(sudo),112(plex),999(docker)
user@computer:~/cloud/.cloud-decrypt$ 
```

**Comment by Dulanic** [comment]
Try changing this in the mount.remote and see if it helps after remount:

`mfs_mounts="${local_decrypt_dir}:${cloud_decrypt_dir}:RO"`
to
`mfs_mounts="${local_decrypt_dir}:${cloud_decrypt_dir}"`

**Comment by Dulanic** [comment]
Shit, I made a mistake too, I left off some commands. Let me put in a PR. You may also have to change the config from 

`mfs_options="-o defaults,nonempty,allow_other,direct_io,use_ino,uid=$uid,gid=$gid"`

to

`mfs_options="-o defaults,nonempty,allow_other,direct_io,use_ino,category.create=ff,category.search=ff,minfreespace=0,uid=$uid,gid=$gid"`

**Comment by Dulanic** [comment]
See these changes: https://github.com/dulanic/cloud-media-scripts/tree/patch-1
This should correct. My bad for messing that up, i compared my process to yours and noticed it was quite a bit different and that I had left out a portion somehow:

`root      8271  0.0  0.0 324024  2360 ?        S<sl 11:15   0:00 mergerfs -o defaults,nonempty,allow_other,direct_io,use_ino,category.create=ff,category.search=ff,minfreespace=0,uid=1000,gid=1000 /local-decrypt/Media:/opt/cloud-media-scripts/.cloud-decrypt /local-media`

**Comment by Antexa** [comment]
Ok, I merged those files. 

Now I got this one : 

```
root@1696351a9d23:~# cp /input/aFile.test /output/
cp: error writing ‘/output/aFile.test’: Illegal seek
cp: failed to extend ‘/output/aFile.test’: Illegal seek
root@1696351a9d23:~#
```

**Comment by Dulanic** [comment]
Can you provide the command being run again?

**Comment by Antexa** [comment]
I retried the previous copy I get the first one error so nothing change. 

```
user@computer:~/cloud$ ps aux | less | grep mergerfs
user   5532  0.0  0.0 610864  2292 ?        Ssl  17:56   0:00 /usr/bin/mergerfs -o defaults,nonempty,allow_other,direct_io,use_ino,uid=1000,gid=1000 /home/user/cloud/.local-decrypt/Media:/home/user/cloud/.cloud-decrypt /home/user/cloud/media
user   5813  0.0  0.0  12788   952 pts/1    S+   17:57   0:00 grep mergerfs
```

**Comment by Dulanic** [comment]
That doesn't have my config changes.

**Comment by Antexa** [comment]
Yep my bad too... It seems that I made a mistake when I edited the file.

**Comment by Dulanic** [comment]
Might need to rerun setup in thinking to update the config? https://github.com/Dulanic/cloud-media-scripts/blob/patch-1/config.template

**Comment by Antexa** [comment]
Seems to be ok. 

Thx @Dulanic 👍

**Comment by Dulanic** [comment]
Thanks for my typo catch @Antexa , glad it's working for you now.
