### ISSUE TITLE
Not an issue 

### ISSUE THREAD

**Issue by zeyoner** [madslundt/cloud-media-scripts#57]
This is not an issue. Apologizes if this isn't the place for this. 

Seeing how you're creating a cloud of content from ex: homeserver. Could there be a script you can run lets say on a Windows desktop at an other location and mount GDrive locally? 

I have already used the current script to mount on linux. This is aimed towards Windows.

**Comment by madslundt** [comment]
Hi there.

I've heard many users are happy with the official Drive File Stream.
Else you can run this docker version in Windows.

**Comment by zeyoner** [comment]
I'd have to try it out in docker. I have the official Drive File Stream. But not sure how that would work due to the file encryption.

**Comment by SilverSix311** [comment]
I would suggest installing Ubuntu for W10 and you can run it from there.
https://docs.microsoft.com/en-us/windows/wsl/install-win10
